#! /bin/sh
#   _
#  | |__  ___ _ ____      ___ __ ___
#  | '_ \/ __| '_ \ \ /\ / / '_ ` _ \
#  | |_) \__ \ |_) \ V  V /| | | | | |
#  |_.__/|___/ .__/ \_/\_/ |_| |_| |_|
#            |_|

#===========
# Autostart
#===========
# Polisch signs
# setxkbmap pl &

# Wallpaper
# setbg &
# hsetroot -solid '#161821'

# Set normal cursor
# xsetroot -cursor_name left_ptr &

# Programs
# remaps &
picom &
sxhkd &
# dunst &
# firefox &
# discord &
# mpd &
feh --bg-fill --randomize /mnt/ogdata/Pictures/Walls/* &
$HOME/.config/polybar/launch.sh &
# alacritty --class scratchpad -e scratch &
# xrandr --output HDMI-A-0 --left-of DisplayPort-0 &
# xrandr --output HDMI-A-0 --rotate left &

#===============
# Configuration
#===============
bspc monitor DisplayPort-0 -d 1 2 3 4 5 
bspc monitor HDMI-A-0 -d 6 7 8 9 10
# bspc desktop -f 1

# Mouse setings
bspc config pointer_modifier mod4
bspc config focus_follows_pointer false
bspc config pointer_action3 resize_side
bspc config pointer_action2 resize_corner
bspc config pointer_action1 move

# Automatic scheme
bspc config automatic_scheme longest_side
bspc config initial_polarity first_child

# Split Ratio
bspc config split_ratio          0.52

# Disable border when is only one window
bspc config single_monocle true

# Gaps && Border
# bspc config borderHDMI-1_width 1
bspc config window_gap 7
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Colorscheme
bspc config normal_border_color "#0f6a99"
bspc config focused_border_color "#3d0f99"
bspc config presel_feedback_color "#1e2132"

#======
# Rule
#======
# bspc rule -a firefox desktop='^2' follow=off
# bspc rule -a qutebrowser desktop='^2'
# bspc rule -a discord desktop='^3'
# bspc rule -a Steam desktop='^5'
# bspc rule -a network-manager state=floating sticky=on
# bspc rule -a *::scratchpad sticky=on state=floating hidden=on locked=on
# bspc rule -a lock  sticky=on state=floating locked=on
# bspc rule -a *::float state=floating
bspc rule -a virtualbox desktop='^0' state=floating
